# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('RGS_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('RGS_status', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('rqd_skset', models.CharField(max_length=200)),
                ('tot_exp', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('IOU', models.CharField(max_length=200)),
                ('req_IOU', models.CharField(max_length=200)),
                ('cust_name', models.CharField(max_length=200)),
                ('ass_date', models.DateTimeField()),
                ('req_branch', models.CharField(max_length=200)),
                ('staff_branch', models.CharField(max_length=200)),
                ('recruiter', models.CharField(default='-', max_length=200)),
                ('remarks', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('no_cv_shared', models.CharField(default='-', max_length=200)),
                ('feedback_pending', models.CharField(default='-', max_length=200)),
                ('screen_rejects_others', models.CharField(default='-', max_length=200)),
                ('shortlists', models.CharField(default='-', max_length=200)),
                ('TR_selects_holds', models.CharField(default='-', max_length=200)),
                ('TR_rejects', models.CharField(default='-', max_length=200)),
                ('MR_selects_holds', models.CharField(default='-', max_length=200)),
                ('MR_rejects', models.CharField(default='-', max_length=200)),
                ('HR_selects_holds', models.CharField(default='-', max_length=200)),
                ('HR_rejects', models.CharField(default='-', max_length=200)),
                ('No_offers_processed', models.CharField(default='-', max_length=200)),
                ('No_offers_released', models.CharField(default='-', max_length=200)),
                ('c1_epno', models.CharField(default='-', max_length=200)),
                ('c1_name', models.CharField(default='-', max_length=200)),
                ('c1_joining_status', models.CharField(default='-', max_length=200)),
                ('c1_DOJ', models.CharField(default='-', max_length=200)),
                ('c2_epno', models.CharField(default='-', max_length=200)),
                ('c2_name', models.CharField(default='-', max_length=200)),
                ('c2_joining_status', models.CharField(default='-', max_length=200)),
                ('c2_DOJ', models.CharField(default='-', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOT', models.DateTimeField()),
                ('branch', models.CharField(default='-', max_length=200)),
                ('who_sourced_name', models.CharField(default='-', max_length=200)),
                ('who_sourced_eno', models.CharField(default='-', max_length=200)),
                ('cand_name', models.CharField(default='-', max_length=200)),
                ('epno', models.CharField(default='-', max_length=200)),
                ('source_dtls', models.CharField(default='-', max_length=200)),
                ('main_skills', models.CharField(default='-', max_length=200)),
                ('ISU_name', models.CharField(default='-', max_length=200)),
                ('customer_name', models.CharField(default='-', max_length=200)),
                ('weekend_weekday', models.CharField(default='-', max_length=200)),
                ('dt_of_interview', models.DateTimeField()),
                ('status', models.CharField(default='-', max_length=200)),
                ('contact_number', models.CharField(default='-', max_length=200)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('tot_yrs_exp', models.CharField(default='-', max_length=200)),
                ('R_exp', models.CharField(default='-', max_length=200)),
                ('current_org', models.CharField(default='-', max_length=200)),
                ('current_loc', models.CharField(default='-', max_length=200)),
                ('pref_loc', models.CharField(default='-', max_length=200)),
                ('current_ctc', models.CharField(default='-', max_length=200)),
                ('exp_ctc', models.CharField(default='-', max_length=200)),
                ('notice_period', models.CharField(default='-', max_length=200)),
                ('TR_status', models.CharField(default='-', max_length=200)),
                ('MR_status', models.CharField(default='-', max_length=200)),
                ('HR_status', models.CharField(default='-', max_length=200)),
                ('offers_made', models.CharField(default='-', max_length=200)),
                ('RGS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Approval')),
            ],
        ),
    ]
