# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='HR_status',
        ),
        migrations.RemoveField(
            model_name='source',
            name='MR_status',
        ),
        migrations.RemoveField(
            model_name='source',
            name='TR_status',
        ),
        migrations.RemoveField(
            model_name='source',
            name='offers_made',
        ),
    ]
