# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170624_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='TR_status',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
