# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_source_tr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='HR_status',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='source',
            name='MR_status',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='source',
            name='offers_made',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
