# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_source_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='DOJ',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
